### ISSUE TITLE
Can't find Sparkling Power sandwiches in search

### ISSUE THREAD

**Issue by starchildluke** [cecilbowen/pokemon-sandwich-simulator#12]
Apologies if I've missed something obvious, but when I tried to search for Sparkling Power via the "search effects" search box, it didn't bring anything up. However, selecting ingredients that makes a Sparkling Power sandwich will display it.

![Simulator not showing sparkling power sandwiches via search](https://user-images.githubusercontent.com/14061573/206533079-282102e4-777d-4004-984b-ad0f2ae55851.png)

![Simulator showing sparkling power sandwiches via manual ingredient selection](https://user-images.githubusercontent.com/14061573/206533099-02a0d478-998d-4ab1-bf0e-dd7e69967cd1.png)

**Comment by cecilbowen** [comment]
search boxes only search through the preset (numbered) recipes in-game.  they are not a "i want a sandwich with x powers/types, now show me how to make it"

**Comment by starchildluke** [comment]
Ah, gotcha! Thanks for the response!
