### ISSUE TITLE
A potential error in rule explanation

### ISSUE THREAD

**Issue by ZeroRin** [cecilbowen/pokemon-sandwich-simulator#13]
https://github.com/cecilbowen/pokemon-sandwich-simulator/blob/fe282589fa691f7a83b600d3a5efdb6664f9a201/src/misc/rules.txt#L20

If the types are assumed to be [grass, fighting, ghost], then  
(1,1,3) -> (grass, grass, ghost)
(grass, grass, fighting) -> (1,1,2)
not sure which one is correct

**Comment by HappyLappy1** [comment]
From what I've heard, that list of rules is outdated. I would trust anything the page actually does over what that says.

**Comment by cecilbowen** [comment]
> https://github.com/cecilbowen/pokemon-sandwich-simulator/blob/fe282589fa691f7a83b600d3a5efdb6664f9a201/src/misc/rules.txt#L20
> 
> If the types are assumed to be [grass, fighting, ghost], then (1,1,3) -> (grass, grass, ghost) (grass, grass, fighting) -> (1,1,2) not sure which one is correct

Going by the line you linked from the old rules, yes, that was a user error by me.  It should have been (1, 1, 3) -> (grass, grass, ghost).  Rules have since been updated, though.
