### ISSUE TITLE
Spanish Version?

### ISSUE THREAD

**Issue by Legarad** [cecilbowen/pokemon-sandwich-simulator#17]
Can you do it in Spanish?
[Spanish Sandwich  Recipe Information.zip](https://github.com/cecilbowen/pokemon-sandwich-simulator/files/10248477/Spanish.Sandwich.Recipe.Information.zip)

Here I leave the information in Spanish of the list of sandwiches in Spanish Language, the ingredients, seasonings, the list of effects and the translation of the Pokemon types

**Comment by cecilbowen** [comment]
I have added Spanish and German languages to the tool, change-able from the bottom of the page.
![image](https://user-images.githubusercontent.com/45740102/208231927-1d974fcc-8d43-417d-8ee4-95ba369fb69b.png)

**Comment by Legarad** [comment]
Thanks, did you get the materials or did you already have them?

**Comment by cecilbowen** [comment]
I have updated the avocado.

**Comment by HappyLappy1** [comment]
If you need it, we have dumps of all the ingredients/condiments in every playable language. Should begin on line 19138 in this dump of the game in [SV] v101 Text Dump\common, which I got here.  https://twitter.com/mattyoukhana_/status/1593450046099292162
going to upload the file here anyway just in case, but yeah.
[[SV] v101 Text Dump.zip](https://github.com/cecilbowen/pokemon-sandwich-simulator/files/10299388/SV.v101.Text.Dump.zip)
