### ISSUE TITLE
Copy to clipboard does not work (Chrome+Mac)

### ISSUE THREAD

**Issue by traisjames** [cecilbowen/pokemon-sandwich-simulator#30]
When using Google Chrome, copy to clipboard shows the message that the copy was successful but the clipboard is not filled.  The console error given is "util.js:949 Async: Could not copy text:  DOMException: Document is not focused."  Given the post [on StackOverflow about this problem](https://stackoverflow.com/questions/69438702/why-does-navigator-clipboard-writetext-not-copy-text-to-clipboard-if-it-is-pro) the issue may be due to the alert you show.  My browser supports what you are doing, but because it fails to work, your fallback is never attempted.

If not done somewhere else, make sure you check for [clipboard write permission](https://stackabuse.com/how-to-copy-to-clipboard-in-javascript-with-the-clipboard-api/)

**Comment by cecilbowen** [comment]
I pushed an attempted fix to this here: https://github.com/cecilbowen/pokemon-sandwich-simulator/commit/c625b4f329c8c9abece5a49bf25526cdad5a7d2f

I don't have a Mac, so I have no way to know for sure if it worked, so if you could verify it, then let me know.

**Comment by traisjames** [comment]
That worked!  Thank you!
