### ISSUE TITLE
Simulated power is not level 2 when power is boosted to 100 exactly

### ISSUE THREAD

**Issue by kkaja123** [cecilbowen/pokemon-sandwich-simulator#8]
When a power's sum is boosted to 100 points, the result is not calculated as level 2 correctly. It remains as level 1. I have confirmed the following recipe in game:

```
Apple-3,Egg-3,Egg-3,Noodles-1,Noodles-1,Noodles-1_Horseradish,Horseradish
```

Simulated result: raid_ice_1, encounter_flying_1, exp_rock_1

Actual result: **raid_ice_2**, encounter_flying_1, exp_rock_1

My guess is that the program checks `>100` instead of `>=100` or maybe the program accidentally ignores the raid power sum since the individual ingredients don't contribute any raid points.

**Comment by HappyLappy1** [comment]
I've been seeing similar results, though I suspect it's more of a case of repeated ingredients causing a penalty of -10 to the powers. 
Some recipes I've tried: 
`Rice-1, Rice-1, Rice-1, Rice-1, Chorizo-3, Chorizo-3, Whipped Cream, Horseradish, Horseradish, Horseradish`
Produces: Encounter Power: Normal Lv. 1, Raid Power: Flying Lv. 1, Humongo Power: Fire Lv. 1
yet 
`Rice-1, Rice-1, Rice-1, Rice-1, Rice-1, Rice-1, Curry Powder, Horseradish, Horseradish, Horseradish`
Produces: Encounter Power: Normal Lv. 2, Humongo Power: Flying Lv. 2, Raid Power: Fighting Lv. 1
I suspect the number of repeated ingredients affects the debuff in some way, and ingredients with less "servings" such as rice contribute less to that debuff.

**Comment by cecilbowen** [comment]
I updated the level calculation a good bit last night, and both of these results now match in-game results.  Let me know if there's still an inconsistency like you mentioned here.

**Comment by kkaja123** [comment]
Issue has been fixed 🥇
