### ISSUE TITLE
Additional Hardcoded Recipe + Recipe Stats (Feature Request? Kind of?)

### ISSUE THREAD

**Issue by HappyLappy1** [cecilbowen/pokemon-sandwich-simulator#9]
We've been able to get exact stats for the hardcoded recipes, including two additional recipes not actually listed in-game.
Chorizo + Salt + Pepper produces a 3 Star sandwich with no powers, because this is what the hardcoded recipe states. 
Tomato + Tomato is impossible because it doesn't contain any condiments, but theoretically it would work the exact same way.
[FoodPowerCombo_array.txt](https://github.com/cecilbowen/pokemon-sandwich-simulator/files/10178979/FoodPowerCombo_array.txt)
I haven't been able to produce any modified hardcoded recipes, but I suspect that if they exist, the process could be "subtract ingredient from hardcoded stats" or "revert to custom recipe." I already tested, dropping a chorizo in the above recipe produces level 1 powers as if not part of a hard-coded recipe. Also, the bug you described involving the Master Dessert Sandwich is likely a result of forgetting to account for that second apple when hardcoding the recipe.

**Comment by HappyLappy1** [comment]
Also, I found a few examples of 1 star sandwiches doing strange things with Herba Mystica. Might be worth looking into.
`Onion|Onion|Onion|Onion|Onion|Onion|Chili Sauce|Sour Herba Mystica|Spicy Herba Mystica|Spicy Herba Mystica`
Produces: Sparkling Power: Psychic Lv. 2, Title Power: Water Lv. 2, Encounter Power: Grass Lv. 2
`Avocado|Avocado|Avocado|Avocado|Avocado|Avocado|Spicy Herba Mystica|Bitter Herba Mystica`
Produces: Sparkling Power: Dragon Lv. 1, None, None
Very interested in helping improve this tool. Been trying to figure out what the problem with this recipe is for a while, but I still have no clue. 
`Cheese|Kiwi|Watercress|Chili Sauce`
Produces: Encounter Power: Poison Lv. 1, Raid Power: Dragon Lv. 1, Item Drop Power: Fire Lv. 1

**Comment by cecilbowen** [comment]
The one star results you described are very interesting.  I had written off all one stars as failures (no effects) because I had not seen any personally, but now after testing your findings, I realize that I hadn't even tried using an herba mystica with my one-star recipes.  Seeing sparkling power with a level less than 3 is weird.  This is all good info, thanks for posting.

Also, in regards to the cheese, kiwi, watercress, chili sauce recipe; I get `Teensy Power: Poison Lv. 1, Item Drop Power: Dragon Lv. 1, Raid Power: Fire Lv. 1` from the sim, which after testing, is exactly what I get in-game.

**Comment by HappyLappy1** [comment]
Interesting, I must have just made a mistake when making it in-game. sorry for troubling you about that then. As for those dumped recipes, I have other files I couldn't really interpret if you're interested in seeing those. Also, if you need help interpreting some of those ingredient/condiment names, I've got that too. "cutted_pine" is pineapple, for example.

**Comment by cecilbowen** [comment]
Sure, you could drop those files if they're related.  The names in the text file you sent seem pretty self-explanatory, but the values in it/the order they each relate to each other isn't clear to me at first glance.  So it would be helpful if you had some insight on that.  The chorizo/salt/pepper result is also interesting, but makes sense, since I realized that hard-coded recipes in this game literally mean that.  Anyways, I'll have to take a better look at all this tonight, thanks again.

**Comment by HappyLappy1** [comment]
Sure! Here's everything sandwich related I have from the game. We suspect the recipe formula itself is hidden in a LUA somewhere, which is why it isn't hidden in there.
[cooking.zip](https://github.com/cecilbowen/pokemon-sandwich-simulator/files/10179609/cooking.zip)
I'm not really good with any of these file types, but here's what I concluded from what's in there.
- Cooking Common Data is either rules that affect sandwich making (like debuffs to powers as a result of duplicate ingredients) or something completely unrelated like mark assigning. 
- Food Power Combo is ingredient and condiment data. Types, Powers, Flavors, etc.  It also contains hardcoded recipes and stats.
- Ingredient/Ingredient Data is ALSO ingredient data, with the same information as Food Power Combo, arranged differently. 
- Ingredient/Ingredient Dish Data is a bunch of coordinates that correspond to different ingredients, and numbers 0-19. I suspect these to be related to collision and/or ingredient physics during the actual sandwich making. Possibly even the rotational orientation of the ingredients as you pick them up out of the bowls. 
- Recipe/Recipe Data is a list of hard-coded recipes the game is capable of displaying to the player in the sandwich menu. It contains the name of the recipe and the ingredients/condiments required to make it. 
- Seasoning/Seasoning Data is ALSO seasoning data, with the same information as Food Power Combo, arranged differently.
- Takara Spice Table (Treasure Spice, AKA Herba Mystica) is another blank. It appears to contain special buffs intended to be given by certain herba mystica, but these buffs appear to be unused. 
Additionally, here's the hard-coded recipes in a more legible format. 
[Sandwich Recipe Conversions.xlsx](https://github.com/cecilbowen/pokemon-sandwich-simulator/files/10179678/Sandwich.Recipe.Conversions.xlsx)
Also, I'm unable to replicate the modified hardcoded recipes you described in rules. Do you have sample recipes like that? For example, I modified the Ultra Five Alarm Sandwich by dropping a piece of Basil
`Basil-3|Chorizo-3|Green Bell Pepper-3|Jalapeño-3|Onion-3|Chili Sauce|Pepper|Mustard`
And got the exact effects the sandwich calculator predicted. I have a simple calculator in sheets that also got the correct result of: Humungo Power Poison Lv. 1, Raid Power Fire Lv. 1, Exp. Point Power Dragon Lv. 1

**Comment by HappyLappy1** [comment]
Any further questions? Might be easier to contact me via discord (Happylappy#5231) than... github issue report. I don't have reddit. Still curious about those modified hardcoded recipes btw.

**Comment by cecilbowen** [comment]
Closing this as the two hidden hard-coded recipes have since been added.
